version: '3.8'

services:
  chatbot-service:
    build: .
    container_name: omnichat-bot
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules